/*
 * USART3.h
 *
 *  Created on: Jan 29, 2020
 *      Author: Mohammed Samir
 */

#ifndef HEADERS_USART3_H_
#define HEADERS_USART3_H_

/*<Includes>*/
#include <MCAL/STM32F103/MCAL_H/MemoryMap.h>
#include <MCAL/STM32F103/MCAL_H/GPIO.h>
#include <MCAL/STM32F103/MCAL_H/EXTI.h>
#include <stdarg.h>
/*</Includes>*/


/*<Definitions>*/
#define USART3_BUS_CLK	 	36000000
#define USART3_PORT			GPIOB
#define USART3_TX_PIN	 	10
#define USART3_RX_PIN		11
/*</Definitions>*/


/*<Bit-Band Pointers>*/
#define USART3_CLOCK_ENABLE  	BITBAND_PERI(RCC_BASE + RCC_APB1ENR_OFFSET, 18)

#define USART3_CR1_UE			BITBAND_PERI(USART3_BASE + USART_CR1_OFFSET, 13)
#define USART3_CR1_M			BITBAND_PERI(USART3_BASE + USART_CR1_OFFSET, 12)

#define USART3_CR1_PCE 			BITBAND_PERI(USART3_BASE + USART_CR1_OFFSET, 10)
#define USART3_CR1_PS  			BITBAND_PERI(USART3_BASE + USART_CR1_OFFSET, 9)
#define USART3_CR1_RXNEIE		BITBAND_PERI(USART3_BASE + USART_CR1_OFFSET, 5)
#define USART3_CR1_TE			BITBAND_PERI(USART3_BASE + USART_CR1_OFFSET, 3)
#define USART3_CR1_RE 			BITBAND_PERI(USART3_BASE + USART_CR1_OFFSET, 2)
#define USART3_CR1_SPK 			BITBAND_PERI(USART3_BASE + USART_CR1_OFFSET, 0)

#define USART3_CR3_DMAT			BITBAND_PERI(USART3_BASE + USART_CR3_OFFSET, 7)
#define USART3_CR3_DMAR			BITBAND_PERI(USART3_BASE + USART_CR3_OFFSET, 6)
#define USART3_CR3_HDSEL		BITBAND_PERI(USART3_BASE + USART_CR3_OFFSET, 3)

#define USART3_SR_TXE  			BITBAND_PERI(USART3_BASE + USART_SR_OFFSET, 7)
#define USART3_SR_TC  			BITBAND_PERI(USART3_BASE + USART_SR_OFFSET, 6)
#define USART3_SR_RXNE 			BITBAND_PERI(USART3_BASE + USART_SR_OFFSET, 5)

#define USART3_CR2_LINEN		BITBAND_PERI(USART3_BASE + USART_CR2_OFFSET, 14)
#define USART3_CR2_S1 			BITBAND_PERI(USART3_BASE + USART_CR2_OFFSET, 13)
#define USART3_CR2_S0 			BITBAND_PERI(USART3_BASE + USART_CR2_OFFSET, 12)
#define USART3_CR2_LBDIE		BITBAND_PERI(USART3_BASE + USART_CR2_OFFSET, 6)
#define USART3_CR2_LBDL 		BITBAND_PERI(USART3_BASE + USART_CR2_OFFSET, 5)
/*</Bit-Band Pointers>*/


/*<Registers Pointers>*/
#define USART3_DR 		(*(volatile unsigned int *)(USART3_BASE + USART_DR_OFFSET))
#define USART3_BRR 		(*(volatile unsigned int *)(USART3_BASE + USART_BRR_OFFSET))
/*</Registers Pointers>*/


/*<Functions' Parameters>*/
#define _U_TX_EN_OFFSET		0
#define U_TX_EN				0 + _U_TX_EN_OFFSET
#define U_RX_EN				1 + _U_TX_EN_OFFSET

#define _U_TX_DE_OFFSET		2
#define U_TX_DE				0 + _U_TX_DE_OFFSET
#define U_RX_DE				1 + _U_TX_DE_OFFSET

#define _U_TX_DMA_EN_OFFSET	4
#define U_TX_DMA_EN			0 + _U_TX_DMA_EN_OFFSET
#define U_RX_DMA_EN			1 + _U_TX_DMA_EN_OFFSET

#define _U_TX_DMA_DE_OFFSET	6
#define U_TX_DMA_DE			0 + _U_TX_DMA_DE_OFFSET
#define U_RX_DMA_DE			1 + _U_TX_DMA_DE_OFFSET

#define _U_TX_INT_EN_OFFSET	8
#define U_TX_INT_EN			0 + _U_TX_INT_EN_OFFSET
#define U_RX_INT_EN			1 + _U_TX_INT_EN_OFFSET

#define _U_TX_INT_DE_OFFSET	10
#define U_TX_INT_DE			0 + _U_TX_INT_DE_OFFSET
#define U_RX_INT_DE			1 + _U_TX_INT_DE_OFFSET

#define _U_PARITY_OFFSET	12
#define U_PARITY_NONE		0 + _U_PARITY_OFFSET
#define U_PARITY_ODD		1 + _U_PARITY_OFFSET
#define U_PARITY_EVEN		2 + _U_PARITY_OFFSET

#define _U_DATA_BITS_OFFSET	15
#define U_DATA_BITS_8		0 + _U_DATA_BITS_OFFSET
#define U_DATA_BITS_9		1 + _U_DATA_BITS_OFFSET

#define _U_STOP_BITS_OFFSET	17
#define U_STOP_BITS_1		0 + _U_STOP_BITS_OFFSET
#define U_STOP_BITS_0_5		1 + _U_STOP_BITS_OFFSET
#define U_STOP_BITS_2		2 + _U_STOP_BITS_OFFSET
#define U_STOP_BITS_1_5		3 + _U_STOP_BITS_OFFSET

#define _U_LINEN_OFFSET		21
#define U_LINEN_SET			0 + _U_LINEN_OFFSET
#define U_LINEN_CLR			1 + _U_LINEN_OFFSET

#define _U_LBDIE_OFFSET		23
#define U_LBDIE_SET			0 + _U_LBDIE_OFFSET
#define U_LBDIE_CLR			1 + _U_LBDIE_OFFSET

#define _U_LBDL_OFFSET		25
#define	U_LBDL_10_BIT		0 + _U_LBDL_OFFSET
#define	U_LBDL_11_BIT		1 + _U_LBDL_OFFSET
/*<Functions' Parameters>*/


#define ON_USART3_REC USART3_IRQHandler


/*<Functions>*/
void USART3_Init(uint32_t Baud_Rate);
void USART3_Init_OneWire(uint32_t Baud_Rate);
void USART3_Init_Adv(uint32_t Baud_Rate, char Num_Of_Args, ...);
void USART3_Chage_BR(uint32_t Baud_Rate);
char USART3_Read(void);
char USART3_Check_Errors(void);
void USART3_Send(char data);
void USART3_Send_Str(char *Str);
void USART3_Send_Ln();
/*</Functions>*/


#endif /* HEADERS_USART3_H_ */
