/*
 * Timer.c
 *
 *  Created on: Dec 18, 2019
 *      Author: Mohammed Samir
 */

#include <MCAL/STM32F103/MCAL_H/GPIO.h>
#include <MCAL/STM32F103/MCAL_H/Timer1.h>

void TMR1_Config(unsigned int PSC, unsigned int ARR, char TMR_CMS, char TMR_UI){

	TMR1_CLOCK_ENABLE = 1;

	TIM1_PSC	 	= PSC - 1;//CLK / (PSC + 1)
	TIM1_ARR	 	= ARR;//Update Event

	TIM1_CR1_CMS0 = ((TMR_CMS - _TMR_CMS_OFFSET)) & 0x01;
	TIM1_CR1_CMS1 = ((TMR_CMS - _TMR_CMS_OFFSET)>>1) & 0x01;

	TIM1_CR1_DIR 	= TMR_DIR_UP_COUNTER - _TMR_DIR_OFFSET;

	TIM1_DIER_UIE 	= TMR_UI - _TMR_UI_OFFSET;//UIF Must Be Cleared

	TIM1_CR1_CEN	= 1;
}

void TMR1_Config_Ext(unsigned int ARR, char TMR_ETP, char ECE, char TMR_ETPS, char TMR_ETF, char TMR_TS, char TMR_SMS, char TMR_UI, char TMR_TI){

	GPIO_Config(GPIOA, PIN_12, MODE_INPUT, CONFIG_INPUT_PULL_DOWN);

	TMR1_CLOCK_ENABLE = 1;

	TIM1_PSC	 	= 720 - 1;
	TIM1_ARR = ARR;

	/*Edge-aligned mode. The counter counts up or down depending on the direction bit (DIR)*/
	TIM1_CR1_CMS0 = 0;
	TIM1_CR1_CMS1 = 0;

	TIM1_CR1_DIR 	= TMR_DIR_UP_COUNTER - _TMR_DIR_OFFSET;

	TIM1_SMCR_ETP = TMR_ETP - _TMR_ETP_OFFSET;

	TIM1_SMCR_ECE = ECE - _TMR_ECE_OFFSET;

	TIM1_SMCR_ETPS0 = (TMR_ETPS - _TMR_ETPS_OFFSET) & 0x01;
	TIM1_SMCR_ETPS1 = (TMR_ETPS - _TMR_ETPS_OFFSET)>>1;

	TIM1_SMCR_ETF0 = (TMR_ETF - _TMR_ETF_OFFSET) & 0x01;
	TIM1_SMCR_ETF1 = ((TMR_ETF - _TMR_ETF_OFFSET)>>1) & 0x01;
	TIM1_SMCR_ETF2 = ((TMR_ETF - _TMR_ETF_OFFSET)>>2) & 0x01;
	TIM1_SMCR_ETF3 = ((TMR_ETF - _TMR_ETF_OFFSET)>>3);

	/*For Mode 1 Only -> ECE = 0*/
	TIM1_SMCR_TS0 = (TMR_TS - _TMR_TS_OFFSET) & 0x01;
	TIM1_SMCR_TS1 = ((TMR_TS - _TMR_TS_OFFSET)>>1) & 0x01;
	TIM1_SMCR_TS2 = ((TMR_TS - _TMR_TS_OFFSET)>>2);

	TIM1_SMCR_SMS0 = (TMR_SMS - _TMR_SMS_OFFSET) & 0x01;
	TIM1_SMCR_SMS1 = ((TMR_SMS - _TMR_SMS_OFFSET)>>1) & 0x01;
	TIM1_SMCR_SMS2 = ((TMR_SMS - _TMR_SMS_OFFSET)>>2);
	/*---------------*/

	TIM1_DIER_UIE 	= TMR_UI - _TMR_UI_OFFSET;
	TIM1_DIER_TIE 	= TMR_TI - _TMR_TI_OFFSET;

	TIM1_CR1_CEN	= 1;
}

void TMR1_Config_Cap(char TMR_CC1S, char TMR_CC1NP, char TMR_CC1P, char TMR_CC2S, char TMR_CC2NP, char TMR_CC2P){

	TMR1_CLOCK_ENABLE = 1;

	GPIO_Config(GPIOA, PIN_8, MODE_INPUT, CONFIG_INPUT_FLOATING);


	TIM1_PSC	 	= 720 - 1;
	TIM1_ARR = 0xFFFF;

	TIM1_SMCR_ECE = TMR_ECE_DISABLE - _TMR_ECE_OFFSET;



	TIM1_SMCR_TS0 = (TMR_TS_TI1FP1 - _TMR_TS_OFFSET) & 0x01;
	TIM1_SMCR_TS1 = ((TMR_TS_TI1FP1 - _TMR_TS_OFFSET)>>1) & 0x01;
	TIM1_SMCR_TS2 = ((TMR_TS_TI1FP1 - _TMR_TS_OFFSET)>>2);

	TIM1_SMCR_SMS0 = (TMR_SMS_RESET - _TMR_SMS_OFFSET) & 0x01;
	TIM1_SMCR_SMS1 = ((TMR_SMS_RESET - _TMR_SMS_OFFSET)>>1) & 0x01;
	TIM1_SMCR_SMS2 = ((TMR_SMS_RESET - _TMR_SMS_OFFSET)>>2);

	/*DMA*/
	//TIM1_DCR = (2<<8) | (13);/*2 Transfers | Reg Num 13 (CCR1)*/
	//TIM1_DIER_CC1DE = 1;/*CC1 DMA request enable*/
	//TIM1_DIER_CC2DE = 1;/*CC2 DMA request enable */
	/*---*/

	TMR1_Config_CC1(TMR_CC1S, TMR_CC1NP, TMR_CC1P);
	TMR1_Config_CC2(TMR_CC2S, TMR_CC2NP, TMR_CC2P);


	TIM1_CR1_CEN	= 1;
}


void TMR1_Config_CC1(char TMR_CC1S, char TMR_CC1NP, char TMR_CC1P){

	TIM1_CCMR1_CC1S0 = (TMR_CC1S - _TMR_CC1S_OFFSET) & 0x01;
	TIM1_CCMR1_CC1S1 = (TMR_CC1S - _TMR_CC1S_OFFSET)>>1;

	TIM1_CCER_CC1NP = TMR_CC1NP - _TMR_CC1NP_OFFSET;

	TIM1_CCER_CC1P = TMR_CC1P - _TMR_CC1P_OFFSET;

	TIM1_DIER_CC1IE = 1;
	TIM1_CCER_CC1E = 1;
}

void TMR1_Config_CC2(char TMR_CC2S, char TMR_CC2NP, char TMR_CC2P){

	TIM1_CCMR1_CC2S0 = (TMR_CC2S - _TMR_CC2S_OFFSET) & 0x01;
	TIM1_CCMR1_CC2S1 = (TMR_CC2S - _TMR_CC2S_OFFSET)>>1;

	TIM1_CCER_CC2NP = TMR_CC2NP - _TMR_CC2NP_OFFSET;

	TIM1_CCER_CC2P = TMR_CC2P - _TMR_CC2P_OFFSET;

	TIM1_DIER_CC2IE = 1;
	TIM1_CCER_CC2E = 1;
}


